"""Shared constants used by agent infrastructure."""

from enum import StrEnum


class ExecutionStatus(StrEnum):
    STARTED = "started"
    SUCCEEDED = "succeeded"
    FAILED = "failed"


MILLISECONDS_PER_SECOND = 1_000
DEFAULT_TOPIC_CATEGORY = "Personal Finance"
GENERATED_DIRECTORY_NAME = "generated"
JSON_FILE_SUFFIX = ".json"
MARKDOWN_FILE_SUFFIX = ".md"
TOPIC_AGENT_NAME = "topic-agent"
CONCEPT_AGENT_NAME = "concept-agent"
RESEARCH_AGENT_NAME = "research-agent"
TOPIC_AGENT_SYSTEM_PROMPT = "topic_agent/system.md"
TOPIC_AGENT_USER_PROMPT = "topic_agent/user.md"
CONCEPT_AGENT_SYSTEM_PROMPT = "concept_agent/system.md"
CONCEPT_AGENT_USER_PROMPT = "concept_agent/user.md"
RESEARCH_AGENT_SYSTEM_PROMPT = "research_agent/system.md"
RESEARCH_AGENT_USER_PROMPT = "research_agent/user.md"
TOPIC_CANDIDATES_KEY = "topics"
TOPICS_DIRECTORY_NAME = "topics"
CONCEPTS_DIRECTORY_NAME = "concepts"
RESEARCH_DIRECTORY_NAME = "research"
SCRIPT_AGENT_NAME = "script-agent"
SCRIPT_AGENT_SYSTEM_PROMPT = "script_agent/system.md"
SCRIPT_AGENT_USER_PROMPT = "script_agent/user.md"
SCRIPTS_DIRECTORY_NAME = "scripts"
DEFAULT_SCRIPT_WORDS_PER_MINUTE = 145
DEFAULT_SCRIPT_VISUAL_PAUSE_SECONDS = 0
DEFAULT_SCRIPT_MIN_WORDS = 600
DEFAULT_SCRIPT_MAX_WORDS = 900
DEFAULT_SCRIPT_MAX_RETRIES = 1
SECTION_DURATION_MISMATCH_SECONDS = 30
REVIEWER_AGENT_NAME = "reviewer-agent"
REVIEWER_AGENT_SYSTEM_PROMPT = "reviewer_agent/system.md"
REVIEWER_AGENT_USER_PROMPT = "reviewer_agent/user.md"
REVIEWS_DIRECTORY_NAME = "reviews"
REVIEW_MIN_WORDS = 600
REVIEW_MAX_WORDS = 900
REVIEW_MIN_DURATION_SECONDS = 240
REVIEW_MAX_DURATION_SECONDS = 390
STORYBOARD_AGENT_NAME = "storyboard-agent"
STORYBOARD_AGENT_SYSTEM_PROMPT = "storyboard_agent/system.md"
STORYBOARD_AGENT_USER_PROMPT = "storyboard_agent/user.md"
STORYBOARDS_DIRECTORY_NAME = "storyboards"
STORYBOARD_VERSION = "1.0"
DEFAULT_STORYBOARD_ASPECT_RATIO = "16:9"
DEFAULT_STORYBOARD_RESOLUTION = "1920x1080"
DEFAULT_STORYBOARD_FRAME_RATE = 30
VOICEOVERS_DIRECTORY_NAME = "voiceovers"
VOICEOVER_MANIFEST_VERSION = "1.0"
DEFAULT_ELEVENLABS_MODEL_ID = "eleven_multilingual_v2"
DEFAULT_ELEVENLABS_OUTPUT_FORMAT = "mp3_44100_128"
DEFAULT_VOICE_STABILITY = 0.5
DEFAULT_VOICE_SIMILARITY_BOOST = 0.75
DEFAULT_VOICE_STYLE = 0.0
DEFAULT_VOICE_USE_SPEAKER_BOOST = True
DEFAULT_VOICEOVER_HOOK_PAUSE_MS = 500
DEFAULT_VOICEOVER_INTRO_PAUSE_MS = 350
DEFAULT_VOICEOVER_SECTION_PAUSE_MS = 400
DEFAULT_VOICEOVER_CONCLUSION_PAUSE_MS = 450
DEFAULT_VOICEOVER_CTA_PAUSE_MS = 350
DEFAULT_VOICEOVER_DISCLAIMER_PAUSE_MS = 250
DEFAULT_FFMPEG_TIMEOUT_SECONDS = 60
DEFAULT_TTS_MAX_RETRIES = 2
